// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions android = FirebaseOptions(
//       apiKey: 'AIzaSyBqWLCWhoGaxZdsVuO_N5AkiMIZlPqo9Tk',
//       appId: '1:805763955875:android:e58a5b1e563c4b392e1316',
//       messagingSenderId: '805763955875',
//       projectId: 'onfast-fbca7',
//       storageBucket: 'onfast-fbca7.appspot.com',
//       androidClientId: '805763955875-njm6pl5smn4pukcce706pl70fqqs9bdm.apps.googleusercontent.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//       apiKey: 'AIzaSyB5bJZzS-PRzqi459RwoBIocJaeM6CvMaQ',
//       appId: '1:805763955875:ios:c2672589623ef1892e1316',
//       messagingSenderId: '805763955875',
//       projectId: 'onfast-fbca7',
//       storageBucket: 'onfast-fbca7.appspot.com',
//       iosClientId: '805763955875-r8e357v13mfgkg1b86qead4mve4v4pf4.apps.googleusercontent.com',
//       iosBundleId: 'com.onfastt',
//   );
//
// }
